### ISSUE TITLE
Feature request: Add 'Update Slider' Function

### ISSUE THREAD

**Issue by emilycritter** [CodyHouse/cd-accessible-img-compare-slider-changelog#1]
I have several sliders that are hidden on initial page load. When they are shown (via toggles) the slider functionality does not work. Can you add a function to reset the sliders dynamically?

**Comment by claudia-romano** [comment]
Hi Emily, the component has been updated to include a public `ComparisonSlider` object that you can use to initialize the slider when it is revealed. You can get the updated code here:
https://codyhouse.co/ds/components/app/accessible-img-compare-slider

You can find more info here:
https://codyhouse.co/ds/components/info/accessible-img-compare-slider#dynamic-initialization

Make sure to remove the `.js-compare-slider` class so that the slider is not initialized at page load. Then listen to your toggle to initialize the slide, something like:
```js
var compSlider = document.getElementById('compare-slider'),
    compSliderInit = false;

toggle.addEventListener('click', function(){
  compSlider.classList.toggle('is-hidden');
  if(!compSliderInit) {
      new ComparisonSlider(compSlider);
      compSliderInit = true;
  }
});
```
The above code does not take into account multiple sliders, but you get an idea of how you should implement it.

Cheers!
